# Generated by Django 3.2.18 on 2023-03-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0019_auto_20230330_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='tipo_cliente',
        ),
    ]
