# Generated by Django 3.2.18 on 2023-04-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0020_auto_20230330_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='tipocredito',
            field=models.PositiveIntegerField(choices=[(0, 'FACTURA'), (1, 'CREDITO FISCAL')], help_text='Seleccione el Tipo de Crédito'),
        ),
        migrations.AlterField(
            model_name='historicalcredito',
            name='tipocredito',
            field=models.PositiveIntegerField(choices=[(0, 'FACTURA'), (1, 'CREDITO FISCAL')], help_text='Seleccione el Tipo de Crédito'),
        ),
    ]
