# Generated by Django 3.2.18 on 2023-04-08 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0011_subactividadeco_catactividadeco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobrox', '0021_auto_20230404_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodocumento', models.CharField(max_length=20)),
                ('nrc', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=250)),
                ('complementodir', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('codactividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recep_codactividad', to='wsfacturae.detallemastercat')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.municipio')),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recep_tipodocum', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reccep_user_creationcc', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Historicalreceptor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nodocumento', models.CharField(max_length=20)),
                ('nrc', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=250)),
                ('complementodir', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('codactividad', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.municipio')),
                ('tipodocumento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical receptor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalemisor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nit', models.CharField(max_length=14)),
                ('nrc', models.CharField(max_length=8)),
                ('dui', models.CharField(max_length=14)),
                ('nombre', models.CharField(max_length=250)),
                ('nombrecomercial', models.CharField(blank=True, max_length=150, null=True)),
                ('complementodir', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('codestablemh', models.CharField(blank=True, max_length=4, null=True)),
                ('codestable', models.CharField(blank=True, max_length=4, null=True)),
                ('codpuntoventamh', models.CharField(blank=True, max_length=4, null=True)),
                ('codpuntoventa', models.CharField(blank=True, max_length=4, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('codactividad', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.municipio')),
                ('tipoestablecimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical emisor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=14)),
                ('nrc', models.CharField(max_length=8)),
                ('dui', models.CharField(max_length=14)),
                ('nombre', models.CharField(max_length=250)),
                ('nombrecomercial', models.CharField(blank=True, max_length=150, null=True)),
                ('complementodir', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('codestablemh', models.CharField(blank=True, max_length=4, null=True)),
                ('codestable', models.CharField(blank=True, max_length=4, null=True)),
                ('codpuntoventamh', models.CharField(blank=True, max_length=4, null=True)),
                ('codpuntoventa', models.CharField(blank=True, max_length=4, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('codactividad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emi_codactividad', to='wsfacturae.detallemastercat')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.municipio')),
                ('tipoestablecimiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emi_tipoestablecimiento', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisor_user_creationcc', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
