# Generated by Django 3.2.18 on 2023-04-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0023_auto_20230408_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emisor',
            old_name='codactividad',
            new_name='actividadeco',
        ),
        migrations.RenameField(
            model_name='historicalemisor',
            old_name='codactividad',
            new_name='actividadeco',
        ),
    ]
