# Generated by Django 3.2.18 on 2023-04-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0024_auto_20230408_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisor',
            name='nit',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='historicalemisor',
            name='nit',
            field=models.CharField(max_length=17),
        ),
    ]
