# Generated by Django 3.2.18 on 2023-04-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0025_auto_20230408_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisor',
            name='celular',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalemisor',
            name='celular',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
