# Generated by Django 3.2.18 on 2023-04-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0011_subactividadeco_catactividadeco'),
        ('cobrox', '0026_auto_20230408_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreceptor',
            name='codactividad',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='codactividad',
        ),
        migrations.AddField(
            model_name='historicalreceptor',
            name='actividadeco',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.actividadeco'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='actividadeco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recep_actividadeco', to='wsfacturae.actividadeco'),
        ),
        migrations.AlterField(
            model_name='historicalreceptor',
            name='complementodir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreceptor',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreceptor',
            name='nrc',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreceptor',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='complementodir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.municipio'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='nrc',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
