# Generated by Django 3.2.18 on 2023-05-04 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0013_auto_20230413_1540'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobrox', '0028_detallefactura_factura_historicalfactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentorelacionadofactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=36)),
                ('fechaemision', models.DateField()),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=17)),
                ('docidentificacion', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=11),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='codigo',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='codtributo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detallefac_codtributo', to='wsfacturae.detallemastercat'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='montodescuento',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='nogravado',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='numitem',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='preciouni',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='psv',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tipoitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detallefac_tipoitem', to='wsfacturae.detallemastercat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tributos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='unimedida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detallefac_unimedida', to='wsfacturae.detallemastercat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='user_creation',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detallefac_user_creationcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='user_last_update',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='ventaexenta',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='ventagravada',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='ventanosuj',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='codigo_generacion',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='descuexenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='descugravada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='descunosuj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='ivaperci1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='ivarete1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_control_dte',
            field=models.CharField(default=1, max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='porcentajedescuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='retete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotalventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='totaldescu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='totalexenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='totalgravada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='totalnosuj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='codigo_generacion',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='descuexenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='descugravada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='descunosuj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='ivaperci1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='ivarete1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='numero_control_dte',
            field=models.CharField(default=1, max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='porcentajedescuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='retete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='subtotalventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='totaldescu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='totalexenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='totalgravada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='totalnosuj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.CreateModel(
            name='ventatercerofactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=17)),
                ('nombre', models.CharField(max_length=250)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.factura')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventater_user_creationcc', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalventatercerofactura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nit', models.CharField(max_length=17)),
                ('nombre', models.CharField(max_length=250)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('factura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cobrox.factura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ventatercerofactura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldocumentorelacionadofactura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=36)),
                ('fechaemision', models.DateField()),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('factura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cobrox.factura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipodocumento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('tipodogeneracion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical documentorelacionadofactura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldocumentoasociadofactura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descdocumento', models.CharField(blank=True, max_length=100, null=True)),
                ('detalledocumento', models.CharField(blank=True, max_length=300, null=True)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('coddocasociado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('factura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cobrox.factura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cobrox.medico')),
                ('medico_tiposervicio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical documentoasociadofactura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldetallefactura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numitem', models.PositiveIntegerField()),
                ('cantidad', models.DecimalField(decimal_places=8, default=1, max_digits=11)),
                ('codigo', models.CharField(max_length=1000)),
                ('preciouni', models.DecimalField(decimal_places=8, max_digits=11)),
                ('montodescuento', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('ventanosuj', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('ventaexenta', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('ventagravada', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('tributos', models.CharField(blank=True, max_length=100, null=True)),
                ('psv', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('nogravado', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('codtributo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('documentorelacionadofactura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cobrox.documentorelacionadofactura')),
                ('factura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cobrox.factura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipoitem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('unimedida', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical detallefactura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='documentorelacionadofactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.factura'),
        ),
        migrations.AddField(
            model_name='documentorelacionadofactura',
            name='tipodocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docrel_tipodocum', to='wsfacturae.detallemastercat'),
        ),
        migrations.AddField(
            model_name='documentorelacionadofactura',
            name='tipodogeneracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docrel_tipogen', to='wsfacturae.detallemastercat'),
        ),
        migrations.AddField(
            model_name='documentorelacionadofactura',
            name='user_creation',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentorel_user_creationcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentorelacionadofactura',
            name='user_last_update',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='documentoasociadofactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descdocumento', models.CharField(blank=True, max_length=100, null=True)),
                ('detalledocumento', models.CharField(blank=True, max_length=300, null=True)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('coddocasociado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_asoc_tipodocum', to='wsfacturae.detallemastercat')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.factura')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.medico')),
                ('medico_tiposervicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docasoc_medtiposer', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docasoc_user_creationcc', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='documentorelacionadofactura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.documentorelacionadofactura'),
            preserve_default=False,
        ),
    ]
