# Generated by Django 3.2.18 on 2023-05-04 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wsfacturae', '0013_auto_20230413_1540'),
        ('cobrox', '0029_auto_20230504_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='retete',
            new_name='montototaloperacion',
        ),
        migrations.RenameField(
            model_name='historicalfactura',
            old_name='retete',
            new_name='montototaloperacion',
        ),
        migrations.AddField(
            model_name='factura',
            name='condicionoperacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detallefac_condope', to='wsfacturae.detallemastercat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='reterenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='saldofavor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='totalletras',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='totalnogravado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='factura',
            name='totapagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='condicionoperacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat'),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='reterenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='saldofavor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='totalletras',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='totalnogravado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='totapagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.CreateModel(
            name='pagosfactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montopago', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('periodo', models.PositiveIntegerField(blank=True, null=True)),
                ('numpagoelectronico', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagosfactura_tipopago', to='wsfacturae.detallemastercat')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.factura')),
                ('plazo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagosfactura_plazo', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagosfactura_user_creationcc', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalpagosfactura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('montopago', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('periodo', models.PositiveIntegerField(blank=True, null=True)),
                ('numpagoelectronico', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('codigo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('factura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cobrox.factura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plazo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pagosfactura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
