# Generated by Django 3.2.18 on 2023-05-11 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0031_apendicefactura_extensionfactura_historicalapendicefactura_historicalextensionfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='aux_aprob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='aux_aprob_date_upd',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='credito',
            name='aux_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='aux_gen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcredito',
            name='aux_aprob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcredito',
            name='aux_aprob_date_upd',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='historicalcredito',
            name='aux_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcredito',
            name='aux_gen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
