# Generated by Django 3.2.18 on 2023-05-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0032_auto_20230511_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpago',
            name='aux_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpago',
            name='aux_gen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='aux_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='aux_gen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
