# Generated by Django 3.2.18 on 2023-11-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0034_auto_20231110_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcreditofinanc',
            name='credito_financia',
        ),
        migrations.RemoveField(
            model_name='historicalcreditofinanc',
            name='credito_nvo',
        ),
        migrations.RemoveField(
            model_name='historicalcreditofinanc',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcreditofinanc',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicalcreditofinanc',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='creditofinanc',
        ),
        migrations.DeleteModel(
            name='Historicalcreditofinanc',
        ),
    ]
