# Generated by Django 3.2.18 on 2023-11-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0035_auto_20231110_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldocumentoasociadofactura',
            name='coddocasociado',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentoasociadofactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentoasociadofactura',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentoasociadofactura',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentoasociadofactura',
            name='medico_tiposervicio',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentoasociadofactura',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentoasociadofactura',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='documentoasociadofactura',
        ),
        migrations.DeleteModel(
            name='Historicaldocumentoasociadofactura',
        ),
    ]
