# Generated by Django 3.2.18 on 2023-11-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0036_auto_20231110_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='codtributo',
        ),
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='documentorelacionadofactura',
        ),
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='tipoitem',
        ),
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='unimedida',
        ),
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='detallefactura',
        ),
        migrations.DeleteModel(
            name='Historicaldetallefactura',
        ),
    ]
