# Generated by Django 3.2.18 on 2023-11-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0037_auto_20231111_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldocumentorelacionadofactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentorelacionadofactura',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentorelacionadofactura',
            name='tipodocumento',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentorelacionadofactura',
            name='tipodogeneracion',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentorelacionadofactura',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentorelacionadofactura',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='documentorelacionadofactura',
        ),
        migrations.DeleteModel(
            name='Historicaldocumentorelacionadofactura',
        ),
    ]
