# Generated by Django 3.2.18 on 2023-11-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0038_auto_20231111_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventatercerofactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='ventatercerofactura',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='ventatercerofactura',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='Historicalventatercerofactura',
        ),
        migrations.DeleteModel(
            name='ventatercerofactura',
        ),
    ]
