# Generated by Django 3.2.18 on 2023-11-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0039_auto_20231111_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalapendicefactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='historicalapendicefactura',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalapendicefactura',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicalapendicefactura',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='apendicefactura',
        ),
        migrations.DeleteModel(
            name='Historicalapendicefactura',
        ),
    ]
