# Generated by Django 3.2.18 on 2023-11-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0040_auto_20231111_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalextensionfactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='historicalextensionfactura',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalextensionfactura',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicalextensionfactura',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='extensionfactura',
        ),
        migrations.DeleteModel(
            name='Historicalextensionfactura',
        ),
    ]
