# Generated by Django 3.2.18 on 2023-11-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0042_auto_20231111_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfactura',
            name='condicionoperacion',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='emisor',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='factura',
        ),
        migrations.DeleteModel(
            name='Historicalfactura',
        ),
    ]
