# Generated by Django 3.2.18 on 2023-11-11 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0043_auto_20231111_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptor',
            name='actividadeco',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='tipodocumento',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='Historicalreceptor',
        ),
        migrations.DeleteModel(
            name='receptor',
        ),
    ]
