# Generated by Django 3.2.18 on 2023-11-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0045_auto_20231111_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcredito_archivo',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='historicalcredito_archivo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcredito_archivo',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicalcredito_archivo',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='credito_archivo',
        ),
        migrations.DeleteModel(
            name='Historicalcredito_archivo',
        ),
    ]
