# Generated by Django 3.2.18 on 2023-11-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0046_auto_20231111_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcliente_archivo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historicalcliente_archivo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcliente_archivo',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicalcliente_archivo',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='cliente_archivo',
        ),
        migrations.DeleteModel(
            name='Historicalcliente_archivo',
        ),
    ]
