# Generated by Django 3.2.18 on 2023-11-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0047_auto_20231111_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medico',
        ),
    ]
