# Generated by Django 3.2.18 on 2023-11-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0050_auto_20231113_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_cliente',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='tipo_cliente',
            name='user_last_update',
        ),
        migrations.DeleteModel(
            name='Historicaltipo_cliente',
        ),
        migrations.DeleteModel(
            name='tipo_cliente',
        ),
    ]
