# Generated by Django 3.2.18 on 2023-03-19 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ws_autenticacion_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_enviado', models.TextField()),
                ('jenviado', models.JSONField(blank=True, null=True)),
                ('jrespuesta', models.JSONField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('tiporespuesta', models.IntegerField(choices=[(-1, 'ERROR'), (1, 'EXITO')], default=1, help_text='Tipo de Respuesta')),
                ('mensajeerror', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
