# Generated by Django 3.2.18 on 2023-04-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0004_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
