# Generated by Django 3.2.18 on 2023-04-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0005_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('nm_estado', models.IntegerField(choices=[(-1, 'INACTIVE'), (1, 'ACTIVE')], default=1, help_text='Activo o Inactivo el Registro')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.IntegerField()),
                ('tipoGeneracion', models.IntegerField()),
                ('numeroDocumento', models.IntegerField()),
                ('fechaEmision', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=200)),
                ('nrc', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('codActividad', models.CharField(max_length=200)),
                ('desActividad', models.CharField(max_length=200)),
                ('nombreComercial', models.CharField(max_length=200)),
                ('tipoEstablecimiento', models.CharField(max_length=200)),
                ('dirdepartamento', models.CharField(max_length=200)),
                ('dirmunicipio', models.CharField(max_length=200)),
                ('dircomplemento', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('codEstableMH', models.CharField(max_length=200)),
                ('codEstable', models.CharField(max_length=200)),
                ('codPuntoVentaMH', models.CharField(max_length=200)),
                ('codPuntoVenta', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=4)),
                ('ambiente', models.CharField(max_length=2)),
                ('tipoDte', models.CharField(max_length=3)),
                ('numeroControl', models.CharField(max_length=10)),
                ('codigoGeneracion', models.CharField(max_length=20)),
                ('tipoModelo', models.CharField(max_length=3)),
                ('tipoOperacion', models.CharField(max_length=1)),
                ('tipoContingencia', models.CharField(max_length=1)),
                ('motivoContin', models.CharField(blank=True, max_length=180, null=True)),
                ('fecEmi', models.DateTimeField()),
                ('horEmi', models.CharField(max_length=8)),
                ('tipoMoneda', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='mastercat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('nm_estado', models.IntegerField(choices=[(-1, 'INACTIVE'), (1, 'ACTIVE')], default=1, help_text='Activo o Inactivo el Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.IntegerField()),
                ('numDocumento', models.CharField(max_length=200)),
                ('nrc', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('codActividad', models.CharField(max_length=200)),
                ('desActividad', models.CharField(max_length=200)),
                ('dirdepartamento', models.CharField(max_length=200)),
                ('dirmunicipio', models.CharField(max_length=200)),
                ('dircomplemento', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('cod_negocio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('nm_estado', models.IntegerField(choices=[(-1, 'INACTIVE'), (1, 'ACTIVE')], default=1, help_text='Activo o Inactivo el Registro')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='detallemastercat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('nm_estado', models.IntegerField(choices=[(-1, 'INACTIVE'), (1, 'ACTIVE')], default=1, help_text='Activo o Inactivo el Registro')),
                ('mastercat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.mastercat')),
            ],
        ),
    ]
