# Generated by Django 3.2.18 on 2023-04-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0006_departamento_detallemastercat_documentorelacionado_emisor_identification_mastercat_municipio_recepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mastercat',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
