# Generated by Django 3.2.18 on 2023-04-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0009_rename_actividadeco_catactividadeco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemactividadeco',
            new_name='actividadeco',
        ),
    ]
