# Generated by Django 3.2.18 on 2023-04-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0010_rename_itemactividadeco_actividadeco'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactividadeco',
            name='catactividadeco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.catactividadeco'),
            preserve_default=False,
        ),
    ]
