# Generated by Django 3.2.18 on 2023-04-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0012_tributo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emisor',
        ),
        migrations.DeleteModel(
            name='Receptor',
        ),
    ]
