# Generated by Django 3.2.18 on 2023-07-19 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wsfacturae', '0014_auto_20230719_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricaldocTributarioElec',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fk_DocAsoc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.otrosdocasoc')),
                ('fk_Emisor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.emisorn')),
                ('fk_Ident', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.identification')),
                ('fk_Receptor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.receptorn')),
                ('fk_VentasTerc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.ventatercero')),
                ('fk_apendicefactura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.apendicefactura')),
                ('fk_cuerpoDoc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.cuerpo')),
                ('fk_docRel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.documentorelacionado')),
                ('fk_extension', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.extension')),
                ('fk_resumen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.resumen')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical doc tributario elec',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='docTributarioElec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('fk_DocAsoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.otrosdocasoc')),
                ('fk_Emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.emisorn')),
                ('fk_Ident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.identification')),
                ('fk_Receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.receptorn')),
                ('fk_VentasTerc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.ventatercero')),
                ('fk_apendicefactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.apendicefactura')),
                ('fk_cuerpoDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.cuerpo')),
                ('fk_docRel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.documentorelacionado')),
                ('fk_extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.extension')),
                ('fk_resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.resumen')),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detallefac_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
