# Generated by Django 3.2.18 on 2023-07-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0015_doctributarioelec_historicaldoctributarioelec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='tipoModelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.detallemastercat'),
        ),
    ]
