# Generated by Django 3.2.18 on 2023-07-19 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wsfacturae', '0019_auto_20230719_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuerpo',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cuerpo',
            name='user_creation',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuerpofactura_user_creationc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuerpo',
            name='user_last_update',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
