# Generated by Django 3.2.18 on 2023-07-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0021_auto_20230719_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpagosfactura',
            name='resumen',
        ),
        migrations.RemoveField(
            model_name='pagosfactura',
            name='resumen',
        ),
        migrations.AddField(
            model_name='resumen',
            name='pagos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.pagosfactura'),
        ),
    ]
