# Generated by Django 3.2.18 on 2023-07-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0022_auto_20230719_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='pagos',
        ),
        migrations.AddField(
            model_name='historicalpagosfactura',
            name='resumen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.resumen'),
        ),
        migrations.AddField(
            model_name='pagosfactura',
            name='resumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.resumen'),
        ),
    ]
