# Generated by Django 3.2.18 on 2023-07-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0023_auto_20230719_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctributarioelec',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldoctributarioelec',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
