# Generated by Django 3.2.18 on 2023-07-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0024_auto_20230719_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='tribuDescripcion',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='tribuValor',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='tribus',
        ),
        migrations.AddField(
            model_name='doctributarioelec',
            name='codigoDocNegocio',
            field=models.CharField(default=115, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldoctributarioelec',
            name='codigoDocNegocio',
            field=models.CharField(default=115, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctributarioelec',
            name='fk_Emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.emisorn'),
        ),
        migrations.AlterField(
            model_name='doctributarioelec',
            name='fk_Receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.receptorn'),
        ),
        migrations.CreateModel(
            name='TribuDocDte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codTributo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.tributo')),
            ],
        ),
        migrations.AddField(
            model_name='doctributarioelec',
            name='fk_TribuDocDte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.tribudocdte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldoctributarioelec',
            name='fk_TribuDocDte',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.tribudocdte'),
        ),
    ]
