# Generated by Django 3.2.18 on 2023-07-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0026_alter_doctributarioelec_fk_tribudocdte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctributarioelec',
            name='fk_TribuDocDte',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_TribuDocDte',
        ),
    ]
