# Generated by Django 3.2.18 on 2023-07-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0029_auto_20230721_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctributarioelec',
            name='codigoDocNegocio',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='codigoDocNegocio',
        ),
    ]
