# Generated by Django 3.2.18 on 2023-07-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0030_auto_20230721_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctributarioelec',
            name='codFacturaEmpresa',
            field=models.CharField(default='COD-11515', max_length=32),
        ),
        migrations.AddField(
            model_name='historicaldoctributarioelec',
            name='codFacturaEmpresa',
            field=models.CharField(default='COD-11515', max_length=32),
        ),
        migrations.CreateModel(
            name='tributoAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_tributo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.tributo')),
            ],
        ),
    ]
