# Generated by Django 3.2.18 on 2023-07-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0031_auto_20230721_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalotrosdocasoc',
            name='medico_tiposervicio',
        ),
        migrations.RemoveField(
            model_name='otrosdocasoc',
            name='medico_tiposervicio',
        ),
        migrations.AddField(
            model_name='medico',
            name='tiposervicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='docasoc_medtipos', to='wsfacturae.detallemastercat'),
        ),
    ]
