# Generated by Django 3.2.18 on 2023-07-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0032_auto_20230721_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctributarioelec',
            name='fk_pagosFactura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.pagosfactura'),
        ),
        migrations.AddField(
            model_name='historicaldoctributarioelec',
            name='fk_pagosFactura',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.pagosfactura'),
        ),
    ]
