# Generated by Django 3.2.18 on 2023-07-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0034_remove_cuerpo_documentorelacionadofactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuerpo',
            name='tributos',
        ),
    ]
