# Generated by Django 3.2.18 on 2023-07-23 16:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wsfacturae', '0035_remove_cuerpo_tributos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuerpo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='cuerpo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cuerpo',
            name='preciouni',
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=25, null=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('preciouni', models.DecimalField(decimal_places=8, max_digits=11)),
                ('date_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('user_creation', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Producto_user_creationc', to=settings.AUTH_USER_MODEL)),
                ('user_last_update', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
