# Generated by Django 3.2.18 on 2023-07-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0036_auto_20230723_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuerpo',
            name='tipoitem',
        ),
        migrations.AddField(
            model_name='cuerpo',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.productos'),
        ),
        migrations.AddField(
            model_name='productos',
            name='tipoitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detallefac_tipoitm', to='wsfacturae.detallemastercat'),
        ),
    ]
