# Generated by Django 3.2.18 on 2023-07-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0037_auto_20230723_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuerpo',
            name='unimedida',
        ),
        migrations.AddField(
            model_name='productos',
            name='unimedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detallefac_unimed', to='wsfacturae.detallemastercat'),
        ),
    ]
