# Generated by Django 3.2.18 on 2023-07-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0038_auto_20230723_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpagosfactura',
            name='resumen',
        ),
        migrations.RemoveField(
            model_name='pagosfactura',
            name='resumen',
        ),
    ]
