# Generated by Django 3.2.18 on 2023-07-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0039_auto_20230723_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpagosfactura',
            name='formaPago',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.detallemastercat'),
        ),
        migrations.AddField(
            model_name='pagosfactura',
            name='formaPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagosfactura_formapag', to='wsfacturae.detallemastercat'),
        ),
    ]
