# Generated by Django 3.2.18 on 2023-07-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0040_auto_20230723_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpagosfactura',
            name='formaPago',
        ),
        migrations.RemoveField(
            model_name='pagosfactura',
            name='formaPago',
        ),
    ]
