# Generated by Django 3.2.18 on 2023-07-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0041_auto_20230723_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctributarioelec',
            name='fk_VentasTerc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.ventatercero'),
        ),
    ]
