# Generated by Django 3.2.18 on 2023-08-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0044_auto_20230815_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonFac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('fk_factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.factura')),
            ],
        ),
    ]
