# Generated by Django 3.2.18 on 2023-08-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0045_jsonfac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfac',
            name='fk_factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalle', to='wsfacturae.factura'),
        ),
    ]
