# Generated by Django 3.2.18 on 2023-08-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0046_alter_jsonfac_fk_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptorn',
            name='catActEco',
        ),
        migrations.RemoveField(
            model_name='receptorn',
            name='depto',
        ),
    ]
