# Generated by Django 3.2.18 on 2023-08-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0048_auto_20230821_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='totalExento',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='totalnoExento',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
