# Generated by Django 3.2.18 on 2023-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0049_auto_20230822_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='totalExento',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='totalnoExento',
        ),
        migrations.AddField(
            model_name='factura',
            name='totalExento',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='totalnoExento',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
