# Generated by Django 3.2.18 on 2023-08-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0050_auto_20230822_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fk_Establecimiento',
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_puntoVenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.puntoventa'),
        ),
    ]
