# Generated by Django 3.2.18 on 2023-08-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0051_auto_20230824_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.detallemastercat')),
            ],
        ),
    ]
