# Generated by Django 3.2.18 on 2023-08-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0052_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fk_Identificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.identificacion'),
        ),
    ]
