# Generated by Django 3.2.18 on 2023-08-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0053_factura_fk_identificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='param_version_dte',
            old_name='tipoDte',
            new_name='ambiente',
        ),
    ]
