# Generated by Django 3.2.18 on 2023-08-28 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0057_productos_tributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='tributo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wsfacturae.tributo'),
        ),
    ]
