# Generated by Django 3.2.18 on 2023-08-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0059_auto_20230829_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param_version_dte',
            name='codigo',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
