# Generated by Django 3.2.18 on 2023-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0060_alter_param_version_dte_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descuTotal',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
