# Generated by Django 3.2.18 on 2023-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0062_auto_20230830_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisorn',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='emisor_images/'),
        ),
    ]
