# Generated by Django 3.2.18 on 2023-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0063_emisorn_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisorn',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded/factura_emisor'),
        ),
    ]
