# Generated by Django 3.2.18 on 2023-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0065_auto_20230831_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisorn',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded/profiles_medicos'),
        ),
        migrations.AlterField(
            model_name='emisorn',
            name='nit',
            field=models.CharField(max_length=18),
        ),
    ]
