# Generated by Django 3.2.18 on 2023-09-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0066_auto_20230901_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptorn',
            name='nodocumento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='receptorn',
            name='nrc',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
