# Generated by Django 3.2.18 on 2023-09-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0067_auto_20230901_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptorn',
            name='gran_contr',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
