# Generated by Django 3.2.18 on 2023-09-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0068_receptorn_gran_contr'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ivaRete',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='reteRenta',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
