# Generated by Django 3.2.18 on 2023-09-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0069_auto_20230904_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisorn',
            name='natural',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
