# Generated by Django 3.2.18 on 2023-09-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0072_factura_subtotalcondescu'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
