# Generated by Django 3.2.18 on 2023-09-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0073_detallefactura_preciounitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='totalDescuento',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
