# Generated by Django 3.2.18 on 2023-09-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0076_auto_20230906_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_DocAsoc',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_Emisor',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_Ident',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_Receptor',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_VentasTerc',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_apendicefactura',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_cuerpoDoc',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_docRel',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_extension',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_pagosFactura',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='fk_resumen',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='historicaldoctributarioelec',
            name='user_last_update',
        ),
        migrations.RemoveField(
            model_name='historicalpagosfactura',
            name='numpagoelectronico',
        ),
        migrations.RemoveField(
            model_name='historicalpagosfactura',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='historicalpagosfactura',
            name='plazo',
        ),
        migrations.RemoveField(
            model_name='historicalpagosfactura',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='pagosfactura',
            name='numpagoelectronico',
        ),
        migrations.RemoveField(
            model_name='pagosfactura',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='pagosfactura',
            name='plazo',
        ),
        migrations.RemoveField(
            model_name='pagosfactura',
            name='referencia',
        ),
        migrations.AddField(
            model_name='historicalpagosfactura',
            name='fk_Factura',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wsfacturae.factura'),
        ),
        migrations.AddField(
            model_name='pagosfactura',
            name='fk_Factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detallePagos', to='wsfacturae.factura'),
        ),
        migrations.DeleteModel(
            name='docTributarioElec',
        ),
        migrations.DeleteModel(
            name='HistoricaldocTributarioElec',
        ),
    ]
