# Generated by Django 3.2.18 on 2023-11-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0077_auto_20230910_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.PositiveIntegerField(blank=True, default=0)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTUAL', 'Porcentual'), ('MONTO', 'Monto'), ('TOTAL', 'Total')], max_length=100)),
                ('valor_descuento', models.DecimalField(decimal_places=8, max_digits=11)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.productos')),
            ],
        ),
    ]
