# Generated by Django 3.2.18 on 2023-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0079_alter_descuento_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='cantidad_producto',
        ),
        migrations.AddField(
            model_name='descuento',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
