# Generated by Django 3.2.18 on 2023-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0080_auto_20231114_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
