# Generated by Django 3.2.18 on 2023-11-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0081_alter_descuento_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
