# Generated by Django 3.2.18 on 2023-11-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0084_alter_descuento_tipo_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='tipo_descuento',
            field=models.CharField(choices=[('MONTO_FACTURA', 'Monto factura'), ('MONTO_ITEM', 'Monto item'), ('PORCENTUAL_FACTURA', 'Porcentual factura'), ('PORCENTUAL_ITEM', 'Porcentual item')], max_length=100),
        ),
    ]
