# Generated by Django 3.2.18 on 2023-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0085_auto_20231115_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
