# Generated by Django 3.2.18 on 2023-11-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0086_alter_descuento_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='descUnidad',
        ),
    ]
