# Generated by Django 3.2.18 on 2023-11-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0087_remove_productos_descunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
