# Generated by Django 3.2.18 on 2023-11-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0088_descuento_tipo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('S', 'Exnto'), ('N', 'Gravado')], max_length=1, null=True),
        ),
    ]
