# Generated by Django 3.2.18 on 2023-11-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0090_alter_descuento_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='montoDescu',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
