# Generated by Django 3.2.18 on 2023-11-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0091_detallefactura_montodescu'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacion',
            name='ambiente',
            field=models.ForeignKey(max_length=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identificacion_ambiente', to='wsfacturae.detallemastercat'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
