# Generated by Django 3.2.18 on 2023-11-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0092_auto_20231130_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacion',
            name='ambiente',
            field=models.ForeignKey(default=0, max_length=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identificacion_ambiente', to='wsfacturae.detallemastercat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='version',
            field=models.IntegerField(default='00'),
            preserve_default=False,
        ),
    ]
