# Generated by Django 3.2.18 on 2023-12-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0094_auto_20231201_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacion',
            name='tipoOperacion',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identificacion_tipooperacion', to='wsfacturae.detallemastercat'),
            preserve_default=False,
        ),
    ]
