# Generated by Django 3.2.18 on 2023-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0096_receptorn_nombrecomercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='totalPagar',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
