# Generated by Django 3.2.18 on 2023-12-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsfacturae', '0099_auto_20231205_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_dte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wsfacturae.estado'),
        ),
    ]
