# Generated by Django 3.2.18 on 2023-04-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('complemento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.IntegerField()),
                ('tipoGeneracion', models.IntegerField()),
                ('numeroDocumento', models.IntegerField()),
                ('fechaEmision', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
