# Generated by Django 3.2.18 on 2023-07-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restser', '0003_detallefactura_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='fk_factura',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restser.detallefactura'),
        ),
    ]
