# Generated by Django 3.2.18 on 2023-07-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restser', '0004_auto_20230724_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fk_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restser.detallefactura'),
        ),
    ]
