# Generated by Django 3.2.18 on 2023-07-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restser', '0008_remove_detallefactura_fk_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='monto',
        ),
    ]
