# Generated by Django 3.2.18 on 2023-07-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restser', '0010_auto_20230725_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='codigo',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
