# Generated by Django 3.2.18 on 2023-08-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restser', '0011_alter_factura_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='fk_factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='restser.factura'),
        ),
    ]
